#include <iostream>
#include "JointState.h"
#include "ForwardKinematics.h"
#include "Validation.h"
#include "Collision.h"
#include "TrajectoryPlanner.h"

#include <vector>

void printJointState(const JointState& j){
    std::cout << "{ "
              << j.U1 << ", "
              << j.U2 << ", "
              << j.R1 << ", "
              << j.R2 << ", "
              << j.P1 << "}\n ";
}

void Part1tests() {

    std::cout << "\n -------PART 1 TESTS------- \n";

    std::vector<JointState> tests =
    {
        //test cases
        {0, 0, 0, 0, 0},
        {45, -90, -90, -90, 60},
        {-45, 90, -135, 45, 0},
        {90, 45, -30, 0, 50},
        {-45, 40, 140, 0, 50},

    };

for (const auto& joints : tests) {
    std::cout << "\nTesting: ";
    printJointState(joints);

    //verify state is within the robot joint limit
    if (!isWithinLimits(joints)) {
        std::cout << "||Results: Unreachable||\n";
        continue;
    }

    //verify state does not cause a collision
    if (collision(joints)){
        std::cout << "||Results: Collision||\n";
        continue;
    }

    //compute cartesian position of the end effector using the forward kinematics model for robot
    Position pos = forwardKinematics(joints);

        //prints final reachable position
    std::cout << "||Results: Reachable||" << "\n";
    std::cout << "X: " << pos.x << "mm" << "\n";
    std::cout << "Y: " << pos.y << "mm" << "\n";
    std::cout << "Z: " << pos.z << "mm" << "\n";
    }

}

void Part2tests() {

    std::cout << "\n -------PART 2 TESTS------- \n";

    std::vector<std::pair<JointState, JointState>> tests =
    {

        //test cases
        {{0, 0, 0, 0, 0}, {45, -90, -90, -90, 50}},
        {{45, -90, -90, -90, 10}, {45, -90, -90, -90, 60}},
        {{0, 0, 0, 0, 0}, {-45, 90, -135, 45, 0}},
        {{45, -10, 40, 0, 0}, {45, -10, 150, 0, 0}},
        {{-90, -90, 150, 30, 0}, {-90, 0, 150, 30, 50}},

    };

    //iterate through each predefined test case
    for (const auto& test : tests) {

        const JointState& origin = test.first;
        const JointState& target = test.second;

        //print starting and final config of the robot joints
        std::cout << "\nOrigin: ";
        printJointState(origin);

        std::cout << "Target: ";
        printJointState(target);

        //generate interpolated trajectroy between origin and target
        //planner makes intermediate joint states over the specified trajectory
        auto trajectory = planTrajectory(origin, target);
    
        //verify both origin and target configs are within the robot joint limits
        if (!isWithinLimits(origin) || !isWithinLimits(target)) {
            std::cout << "Trajectory Size: " << trajectory.size() << "\n";

            std::cout << "||Result: Unreachable||\n";
            continue; //skip collision checking and onto next test if unreachable.
        }

        //displlay number of interpolataed trajectory states generated by planner
        std::cout << "Trajectory Size: " << trajectory.size() << "\n";
        

        //if origin or target state cause a collision then collision is printed otherwise reachable
        if (collision(origin) || collision(target)) {
            std::cout << "||Result: Collision||\n";
        }
        else {
            std::cout << "||Result: Reachable||\n";
        }
    }//possible to get reachable reading with intermediate collisions since required only to print warnings
}

int main()
{
    Part1tests();
    Part2tests();

    return 0;
}